# Generated by Django 3.0.3 on 2020-05-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100, verbose_name='Название статьи')),
                ('project_description', models.TextField(verbose_name='Название статьи')),
                ('project_ignore', models.BigIntegerField(verbose_name='Игнорирование первых строк')),
                ('project_limit', models.BigIntegerField(verbose_name='Лимит загрузки')),
                ('project_title', models.BigIntegerField(verbose_name='Строка с заголовками')),
                ('project_automatic', models.BooleanField(verbose_name='Автоматическое определение типов данных')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
    ]
